DROP TABLE omtrace_out;
--
------------------------------------------------------------------------------
-- omtrace_out table.
-- Table to hold trace messages generated by the omtrace package.
------------------------------------------------------------------------------
CREATE TABLE omtrace_out (program_id VARCHAR2(30),
                          line_id    NUMBER,
                          user_db    VARCHAR2(30),
                          user_os    VARCHAR2(30),
                          message    VARCHAR2(4000),
                          timestamp  DATE);
--
-- Create a primary key to ensure that line IDs are not duplicated for a
-- given user/program combination.
ALTER TABLE omtrace_out
ADD CONSTRAINT omtrace_out_pk PRIMARY KEY (program_id,
                                           line_id,
                                           user_db,
                                           user_os);
--
-- Create a public synonym for omtrace_out.
DROP PUBLIC SYNONYM omtrace_out;
--
CREATE PUBLIC SYNONYM omtrace_out FOR omtrace_out;